module.exports = {
  STAFF_ERROR: {
    DUPLICATED_USER: "DUPLICATED_USER",
    DUPLICATED_USER_EMAIL: "DUPLICATED_USER_EMAIL",
    DUPLICATED_USER_PHONE: "DUPLICATED_USER_PHONE",
    NOT_AUTHORIZED: "NOT_AUTHORIZED",
    USER_LOCKED: "USER_LOCKED",
    USERNAME_OR_PASSWORD_NOT_MATCH: "USERNAME_OR_PASSWORD_NOT_MATCH",
  },
  STAFF_ROLE: {
    MANAGE_SYSTEM: "MANAGE_SYSTEM",
    MANAGE_USER: "MANAGE_USER",
    MANAGE_STAFF: "MANAGE_STAFF",
  },
};
