module.exports = {
  jp: {
    traffic_data: "交通データ",
    intersection: "交差点",
    report_time: "レポート時間",
    from_date: "開始日",
    to_date: "終了日",
    time: "時間",
    country: "国",
    city: "市",
    intersection_name: "交差点名",
    camera_id: "カメラID",
    ip_address: "IPアドレス",
    vehicle_l: "車両 L",
    vehicle_m: "車両 M",
    vehicle_s: "車両 S",
  },
  vn: {
    traffic_data: "Dữ liệu giao thông",
    intersection: "Giao thông",
    report_time: "Thời gian báo cáo",
    from_date: "Từ ngày",
    to_date: "Đến ngày",
    time: "Thời gian",
    country: "Quốc gia",
    city: "Thành phố",
    intersection_name: "Tên giao thông",
    camera_id: "Mã camera",
    ip_address: "Địa chỉ IP",
    vehicle_l: "Xe lớn",
    vehicle_m: "Xe trung bình",
    vehicle_s: "Xe nhỏ"
  },
  en: {
    traffic_data: "Traffic Data",
    intersection: "Intersection",
    report_time: "Report Time",
    from_date: "From Date",
    to_date: "To Date",
    time: "Time",
    country: "Country",
    city: "City",
    intersection_name: "Intersection Name",
    camera_id: "Camera ID",
    ip_address: "IP Address",
    vehicle_l: "Vehicle L",
    vehicle_m: "Vehicle M",
    vehicle_s: "Vehicle S"
  }
}