module.exports = {
  USER_VERIFY_INFO_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3
  },
  USER_SEX: {
    MALE: 0,
    FEMALE: 1
  },
  USER_TYPE: {
    PERSONAL: 1,
    REALESTATEBROKER: 2
  },
  USER_VERIFY_EMAIL_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3
  },
  USER_VERIFY_PHONE_NUMBER_STATUS: {
    NOT_VERIFIED: 0,
    IS_VERIFIED: 1,
    VERIFYING: 2,
    REJECTED: 3
  },
  USER_MEMBER_LEVEL: {
    MEMBER: "Member",
    AGENCY: "Agency",
  },
  USER_ERROR: {
    DUPLICATED_USER: "DUPLICATED_USER",
    DUPLICATED_USER_EMAIL: "DUPLICATED_USER_EMAIL",
    DUPLICATED_USER_PHONE: "DUPLICATED_USER_PHONE",
    INVALID_REFER_USER: "INVALID_REFER_USER",
    NOT_AUTHORIZED: "NOT_AUTHORIZED",
    USER_LOCKED: "USER_LOCKED",
    REFER_USER_NOT_FOUND: "REFER_USER_NOT_FOUND",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    WRONG_PASSWORD: "WRONG_PASSWORD"
  }
}